import { z } from "zod";
import { createCrudRouter } from "../../http/createCrudRouter.js";

const furnitureSchema = z.object({
  id: z.string().min(1).max(32),
  name: z.string().min(1).max(64),
  map_id: z.string().min(1).max(32),
  kind: z.enum([
    "table",
    "chair",
    "barrel",
    "crate",
    "bookshelf",
    "hill",
    "hillB",
    "hillC",
    "hillsA",
    "hillsATrees",
    "hillsB",
    "hillsBTrees",
    "hillsC",
    "hillsCTrees",
    "rock",
    "rockB",
    "rockC",
    "rockD",
    "rockE",
    "tree",
    "treeB",
    "treeACut",
    "treeBCut",
    "treesACut",
    "treesALarge",
    "treesAMedium",
    "treesASmall",
    "treesBCut",
    "treesBLarge",
    "treesBMedium",
    "treesBSmall",
    "mountainA",
    "mountainB",
    "mountainC",
    "mountainAGrass",
    "mountainAGrassTrees",
    "mountainBGrass",
    "mountainBGrassTrees",
    "mountainCGrass",
    "mountainCGrassTrees",
    "cloudBig",
    "cloudSmall",
    "waterlilyA",
    "waterlilyB",
    "waterplantA",
    "waterplantB",
    "waterplantC",
    "hexBarrel",
    "bucketArrows",
    "bucketEmpty",
    "bucketWater",
    "hexCrateBigA",
    "hexCrateSmallA",
    "hexCrateBigB",
    "hexCrateSmallB",
    "hexCrateLongA",
    "hexCrateLongB",
    "hexCrateLongC",
    "hexCrateLongEmpty",
    "hexCrateOpen",
    "flagBlue",
    "flagGreen",
    "flagRed",
    "flagYellow",
    "ladder",
    "pallet",
    "resourceLumber",
    "resourceStone",
    "sack",
    "archeryTarget",
    "tent",
    "weaponrack",
    "wheelbarrow",
  ]),
  x: z.number(),
  z: z.number(),
  rotation_y: z.number().default(0),
  color: z.string().min(1).max(16),
  y_offset: z.number().default(0),
});
const updateSchema = furnitureSchema.omit({ id: true }).partial();

// No checkDeletable - nothing references a furniture row by id, it's a leaf row (purely
// decorative geometry placed on a map, same as structures/waypoints).
export const furnitureRouter = createCrudRouter("furniture", { createSchema: furnitureSchema, updateSchema });
