export type FieldType = "text" | "textarea" | "number" | "boolean" | "select" | "json" | "reference" | "multiselect" | "effectList";

export interface FieldSchema {
  key: string; // matches the admin API's field name (snake_case, mirrors the DB column)
  label: string;
  type: FieldType;
  options?: string[]; // for "select" - plain string options, value === label
  // for "select" - a labeled numeric option list instead of options above (e.g. "60°" showing in
  // the dropdown but submitting the number 1.0471975511965976) - takes priority over `options`
  // when both are set.
  numberOptions?: { value: number; label: string }[];
  referenceEntity?: string; // for "reference"/"multiselect" - which entity's list to pick from
  optional?: boolean;
}

export interface EntitySchema {
  key: string; // admin API path segment, e.g. "enemy-types"
  label: string;
  displayField: string; // which field to show alongside the id in tables/reference dropdowns
  fields: FieldSchema[];
  hasActivate?: boolean; // maps/dungeons - "exactly one active" is managed via a dedicated action
  hidden?: boolean; // no sidebar nav link - registered only so the generic CRUD helpers work for it
}

export const ENTITIES: EntitySchema[] = [
  {
    key: "classes",
    label: "Classes",
    displayField: "name",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Name", type: "text" },
      { key: "main_stat", label: "Main Stat", type: "select", options: ["strength", "dexterity", "intellect"] },
      { key: "role", label: "Role", type: "select", options: ["tank", "healer", "dps"] },
    ],
  },
  {
    key: "spells",
    label: "Spells",
    displayField: "name",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "class_id", label: "Class", type: "reference", referenceEntity: "classes" },
      { key: "name", label: "Name", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "effect_type", label: "Effect Type", type: "select", options: ["damage", "heal", "dispel", "interrupt"] },
      { key: "target_type", label: "Target Type", type: "select", options: ["enemy", "ally", "self", "ground"] },
      { key: "amount", label: "Amount", type: "number", optional: true },
      { key: "aoe_radius", label: "AoE Radius", type: "number", optional: true },
      { key: "interrupts_cast", label: "Interrupts Cast", type: "boolean", optional: true },
      { key: "cooldown_ms", label: "Cooldown (ms)", type: "number" },
      { key: "cast_time_ms", label: "Cast Time (ms)", type: "number" },
      { key: "range", label: "Range", type: "number" },
      { key: "projectile_speed", label: "Projectile Speed", type: "number", optional: true },
      {
        // The composable path - additive, see shared's SpellDef.effects doc comment. Blank means
        // "use effect_type/target_type/amount/aoe_radius/interrupts_cast above exactly as before".
        key: "effects",
        label: "Composable Effects (advanced - overrides the fields above when set)",
        type: "effectList",
        optional: true,
      },
    ],
  },
  {
    key: "items",
    label: "Items",
    displayField: "name",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Name", type: "text" },
      {
        key: "slot",
        label: "Slot",
        type: "select",
        options: ["weapon", "offHand", "head", "neck", "shoulders", "armor", "hands", "waist", "legs", "feet", "ring", "trinket"],
      },
      { key: "bonuses", label: "Bonuses", type: "json" },
      { key: "icon", label: "Icon (emoji)", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "base_price", label: "Base Price", type: "number" },
    ],
  },
  {
    key: "talents",
    label: "Talents",
    displayField: "name",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "class_id", label: "Class", type: "reference", referenceEntity: "classes" },
      { key: "name", label: "Name", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "max_rank", label: "Max Rank", type: "number" },
      { key: "effect", label: "Effect", type: "json" },
      { key: "tier", label: "Tier (tree row, 1-based)", type: "number" },
      { key: "column_index", label: "Column (0-based, within the row)", type: "number" },
      {
        key: "prerequisite_talent_id",
        label: "Prerequisite Talent (must have 1+ rank to unlock this node)",
        type: "reference",
        referenceEntity: "talents",
        optional: true,
      },
    ],
  },
  {
    key: "enemy-types",
    label: "Enemy Types",
    displayField: "name",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Name", type: "text" },
      { key: "behavior", label: "Behavior", type: "select", options: ["melee", "caster", "boss"] },
      { key: "xp_reward", label: "XP Reward", type: "number" },
      { key: "gold_reward", label: "Gold Reward", type: "number" },
      { key: "stats", label: "Stats (shape depends on behavior)", type: "json" },
      {
        key: "model_id",
        label: "Model (blank = default goblin)",
        type: "select",
        optional: true,
        options: ["skeletonWarrior", "skeletonMage", "skeletonRogue", "skeletonMinion"],
      },
    ],
  },
  {
    key: "enemy-spawns",
    label: "Enemy Spawns",
    displayField: "id",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "map_id", label: "Map", type: "reference", referenceEntity: "maps" },
      { key: "enemy_type_id", label: "Enemy Type", type: "reference", referenceEntity: "enemy-types" },
      { key: "x", label: "X", type: "number" },
      { key: "z", label: "Z", type: "number" },
      { key: "respawn_ms", label: "Respawn (ms)", type: "number", optional: true },
    ],
  },
  {
    key: "enemy-spawn-zones",
    label: "Enemy Spawn Zones",
    displayField: "id",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "map_id", label: "Map", type: "reference", referenceEntity: "maps" },
      { key: "enemy_type_ids", label: "Enemy Types (pool)", type: "multiselect", referenceEntity: "enemy-types" },
      { key: "x", label: "X", type: "number" },
      { key: "z", label: "Z", type: "number" },
      { key: "radius", label: "Radius", type: "number" },
      { key: "max_population", label: "Max Population", type: "number" },
      { key: "respawn_ms", label: "Respawn (ms)", type: "number", optional: true },
      { key: "wander_radius", label: "Wander Radius (blank = default)", type: "number", optional: true },
      { key: "leash_range", label: "Leash Range (blank = default)", type: "number", optional: true },
    ],
  },
  {
    key: "npcs",
    label: "NPCs",
    displayField: "name",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Name", type: "text" },
      { key: "x", label: "X", type: "number" },
      { key: "z", label: "Z", type: "number" },
      { key: "y_offset", label: "Y Offset", type: "number", optional: true },
      { key: "map_id", label: "Map", type: "reference", referenceEntity: "maps" },
      {
        key: "vendor_item_ids",
        label: "Sells (leave empty if not a vendor)",
        type: "multiselect",
        referenceEntity: "items",
        optional: true,
      },
    ],
  },
  {
    key: "quests",
    label: "Quests",
    displayField: "name",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Name", type: "text" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "giver_npc_id", label: "Giver NPC", type: "reference", referenceEntity: "npcs" },
      { key: "objective_enemy_type_id", label: "Objective Enemy Type", type: "reference", referenceEntity: "enemy-types" },
      { key: "objective_count", label: "Objective Count", type: "number" },
      { key: "reward_xp", label: "Reward XP", type: "number" },
      { key: "reward_item_id", label: "Reward Item", type: "reference", referenceEntity: "items", optional: true },
    ],
  },
  {
    key: "maps",
    label: "Maps",
    displayField: "name",
    hasActivate: true,
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Name", type: "text" },
      { key: "kind", label: "Kind", type: "select", options: ["overworld", "dungeon"] },
      { key: "half_extent", label: "Half Extent", type: "number" },
      { key: "portal_x", label: "Portal X", type: "number", optional: true },
      { key: "portal_z", label: "Portal Z", type: "number", optional: true },
      { key: "boss_arena_x", label: "Boss Arena X", type: "number", optional: true },
      { key: "boss_arena_z", label: "Boss Arena Z", type: "number", optional: true },
      { key: "boss_arena_radius", label: "Boss Arena Radius", type: "number", optional: true },
    ],
  },
  {
    key: "structures",
    label: "Structures",
    displayField: "name",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Name", type: "text" },
      { key: "map_id", label: "Map", type: "reference", referenceEntity: "maps" },
      { key: "kind", label: "Kind", type: "select", options: ["wall", "door", "tower", "gate", "building", "lamp"] },
      { key: "x", label: "X", type: "number" },
      { key: "z", label: "Z", type: "number" },
      { key: "rotation_y", label: "Rotation Y (radians)", type: "number", optional: true },
      { key: "width", label: "Width (ignored for kind=building)", type: "number" },
      { key: "depth", label: "Depth (ignored for kind=building)", type: "number" },
      { key: "height", label: "Height (ignored for kind=building)", type: "number" },
      { key: "color", label: "Color (hex, ignored for kind=building)", type: "text" },
      { key: "y_offset", label: "Y Offset", type: "number", optional: true },
      {
        key: "model_id",
        label: "Model ID (building: see BUILDING_MODELS; lamp: lampPost or lampCeiling, see Structure.ts's buildLamp)",
        type: "select",
        optional: true,
        options: [
          "lampPost",
          "lampCeiling",
          "building_archeryrange_blue",
          "building_barracks_blue",
          "building_blacksmith_blue",
          "building_castle_blue",
          "building_church_blue",
          "building_home_A_blue",
          "building_home_B_blue",
          "building_lumbermill_blue",
          "building_market_blue",
          "building_mine_blue",
          "building_tavern_blue",
          "building_tower_A_blue",
          "building_tower_base_blue",
          "building_tower_B_blue",
          "building_tower_catapult_blue",
          "building_watermill_blue",
          "building_well_blue",
          "building_windmill_blue",
          "building_archeryrange_green",
          "building_barracks_green",
          "building_blacksmith_green",
          "building_castle_green",
          "building_church_green",
          "building_home_A_green",
          "building_home_B_green",
          "building_lumbermill_green",
          "building_market_green",
          "building_mine_green",
          "building_tavern_green",
          "building_tower_A_green",
          "building_tower_base_green",
          "building_tower_B_green",
          "building_tower_catapult_green",
          "building_watermill_green",
          "building_well_green",
          "building_windmill_green",
          "building_archeryrange_red",
          "building_barracks_red",
          "building_blacksmith_red",
          "building_castle_red",
          "building_church_red",
          "building_home_A_red",
          "building_home_B_red",
          "building_lumbermill_red",
          "building_market_red",
          "building_mine_red",
          "building_tavern_red",
          "building_tower_A_red",
          "building_tower_base_red",
          "building_tower_B_red",
          "building_tower_catapult_red",
          "building_watermill_red",
          "building_well_red",
          "building_windmill_red",
          "building_archeryrange_yellow",
          "building_barracks_yellow",
          "building_blacksmith_yellow",
          "building_castle_yellow",
          "building_church_yellow",
          "building_home_A_yellow",
          "building_home_B_yellow",
          "building_lumbermill_yellow",
          "building_market_yellow",
          "building_mine_yellow",
          "building_tavern_yellow",
          "building_tower_A_yellow",
          "building_tower_base_yellow",
          "building_tower_B_yellow",
          "building_tower_catapult_yellow",
          "building_watermill_yellow",
          "building_well_yellow",
          "building_windmill_yellow",
          "building_bridge_A",
          "building_bridge_B",
          "building_destroyed",
          "building_dirt",
          "building_grain",
          "building_scaffolding",
          "building_stage_A",
          "building_stage_B",
          "building_stage_C",
          "fence_stone_straight",
          "fence_stone_straight_gate",
          "fence_wood_straight",
          "fence_wood_straight_gate",
          "wall_corner_A_gate",
          "wall_corner_A_inside",
          "wall_corner_A_outside",
          "wall_corner_B_inside",
          "wall_corner_B_outside",
          "wall_straight",
          "wall_straight_gate",
        ],
      },
      {
        key: "light_intensity",
        label: "Light Intensity (lamp only, 0-3ish, blank = default)",
        type: "number",
        optional: true,
      },
    ],
  },
  {
    key: "waypoints",
    label: "Waypoints",
    displayField: "name",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Name", type: "text" },
      { key: "map_id", label: "Map", type: "reference", referenceEntity: "maps" },
      { key: "x", label: "X", type: "number" },
      { key: "z", label: "Z", type: "number" },
    ],
  },
  {
    key: "furniture",
    label: "Furniture",
    displayField: "name",
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Name", type: "text" },
      { key: "map_id", label: "Map", type: "reference", referenceEntity: "maps" },
      {
        key: "kind",
        label: "Kind",
        type: "select",
        options: [
          "table",
          "chair",
          "barrel",
          "crate",
          "bookshelf",
          "hill",
          "hillB",
          "hillC",
          "hillsA",
          "hillsATrees",
          "hillsB",
          "hillsBTrees",
          "hillsC",
          "hillsCTrees",
          "rock",
          "rockB",
          "rockC",
          "rockD",
          "rockE",
          "tree",
          "treeB",
          "treeACut",
          "treeBCut",
          "treesACut",
          "treesALarge",
          "treesAMedium",
          "treesASmall",
          "treesBCut",
          "treesBLarge",
          "treesBMedium",
          "treesBSmall",
          "mountainA",
          "mountainB",
          "mountainC",
          "mountainAGrass",
          "mountainAGrassTrees",
          "mountainBGrass",
          "mountainBGrassTrees",
          "mountainCGrass",
          "mountainCGrassTrees",
          "cloudBig",
          "cloudSmall",
          "waterlilyA",
          "waterlilyB",
          "waterplantA",
          "waterplantB",
          "waterplantC",
          "hexBarrel",
          "bucketArrows",
          "bucketEmpty",
          "bucketWater",
          "hexCrateBigA",
          "hexCrateSmallA",
          "hexCrateBigB",
          "hexCrateSmallB",
          "hexCrateLongA",
          "hexCrateLongB",
          "hexCrateLongC",
          "hexCrateLongEmpty",
          "hexCrateOpen",
          "flagBlue",
          "flagGreen",
          "flagRed",
          "flagYellow",
          "ladder",
          "pallet",
          "resourceLumber",
          "resourceStone",
          "sack",
          "archeryTarget",
          "tent",
          "weaponrack",
          "wheelbarrow",
        ],
      },
      { key: "x", label: "X", type: "number" },
      { key: "z", label: "Z", type: "number" },
      { key: "rotation_y", label: "Rotation Y (radians)", type: "number", optional: true },
      { key: "color", label: "Color (hex)", type: "text" },
      { key: "y_offset", label: "Y Offset", type: "number", optional: true },
    ],
  },
  {
    // hidden: driven entirely by the Map Editor's tile palette instead of a sidebar table view -
    // registered only so listEntities/createEntity/updateEntity/deleteEntity (already fully
    // generic) work for it without any special-casing. Also doubles as the inspector form for a
    // hand-placed coast tile the map editor's own click-to-select flow selects directly (see
    // MapEditor.tsx's "hex-tiles" SelectableType case) - the `rotation` field below is how coast
    // tiles get their manual rotation, since there's no automatic placement for them at all.
    key: "hex-tiles",
    label: "Hex Tiles",
    displayField: "id",
    hidden: true,
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "map_id", label: "Map", type: "reference", referenceEntity: "maps" },
      { key: "q", label: "Q", type: "number" },
      { key: "r", label: "R", type: "number" },
      {
        key: "kind",
        label: "Kind",
        type: "select",
        options: ["grass", "water", "road", "river", "coastCornerLight", "coastNarrowEdge", "coastHalf", "coastMostly"],
      },
      {
        // A hexagon's outline only lines up flush with its neighbors at 60-degree steps, so unlike
        // structures/furniture's free-form rotation_y, this is constrained to the 6 hex-aligned
        // angles - anything else would leave the tile's own hex edge misaligned with its neighbors.
        key: "rotation",
        label: "Rotation (coast tiles only)",
        type: "select",
        optional: true,
        numberOptions: [
          { value: 0, label: "0°" },
          { value: Math.PI / 3, label: "60°" },
          { value: (2 * Math.PI) / 3, label: "120°" },
          { value: Math.PI, label: "180°" },
          { value: (4 * Math.PI) / 3, label: "240°" },
          { value: (5 * Math.PI) / 3, label: "300°" },
        ],
      },
      {
        key: "elevation",
        label: "Elevation (any kind, blank = ground level)",
        type: "number",
        optional: true,
      },
      {
        // Same hex-alignment constraint as coast tiles' `rotation` above - a ramp's own footprint
        // only lines up with a neighbor's edge at 60-degree steps, so this reuses the same fixed
        // set of options rather than a free-form angle.
        key: "ramp_rotation",
        label: "Ramp Direction (grass only, blank = no ramp)",
        type: "select",
        optional: true,
        numberOptions: [
          { value: 0, label: "0°" },
          { value: Math.PI / 3, label: "60°" },
          { value: (2 * Math.PI) / 3, label: "120°" },
          { value: Math.PI, label: "180°" },
          { value: (4 * Math.PI) / 3, label: "240°" },
          { value: (5 * Math.PI) / 3, label: "300°" },
        ],
      },
    ],
  },
  {
    key: "dungeons",
    label: "Dungeons",
    displayField: "name",
    hasActivate: true,
    fields: [
      { key: "id", label: "ID", type: "text" },
      { key: "name", label: "Name", type: "text" },
      { key: "map_id", label: "Map", type: "reference", referenceEntity: "maps" },
      { key: "party_size", label: "Party Size", type: "number" },
      { key: "composition", label: "Composition (Record<role, count>)", type: "json" },
      { key: "spawns", label: "Spawns (fixed spawn points; one boss-behavior entry ends the run)", type: "json" },
    ],
  },
];
